[project]
name = "mcp-memos"
version = "0.1.0"
description = "A MCP server for interacting with Memos."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.76.0",
]

[dependency-groups]
dev = [
    "googleapis-common-protos>=1.71.0",
    "grpcio-tools>=1.76.0",
]
